name: Modelops deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ml_ci_cd]
jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: python version
      run: python --version
#update Github Action - pip install
    - name: pip install
      run: pip install -r requirements.txt
#update Github Action - train model
    - name: train model
      run: python model/train.py
#update Github Action -  docker build
    - name: docker build
      run: docker build -t ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.sha}} .
